### ISSUE TITLE
Frontend configurability settings

### ISSUE THREAD

**Issue by marrus-sh** [glitch-soc/mastodon#23]
## Tasklist

- [x] Create settings modal (see #39)
    - Implemented in 595c6de32c052f2a5e21307a0e43a6bd5d4b5c88
- [ ] Redefine all of Mastodon's colours using semantic variables [eg, `ui-body-text`, `ui-header-text`, `ui-column-color`, and so forth] so that these can be easily changed independently.
- [ ] Define new `light-mode` and `high-contrast` values for the above.
- [ ] Define mixins in the manner of the ones already currently used for multi-/single-column layout for various options
    - [ ] For `reduce-animation`
    - [ ] For `no-transparency`
    - [ ] For `high-contrast`
    - [ ] For `light-mode`
        - For these latter two, perhaps redefine the semantic variables above inside the mixin; eg:
            ```scss
            [[content]]
            .light-mode & {
                $redefined-color: #074e4c;
                [[content]]
            }
            ```
- [ ] Apply mixins to CSS
- [ ] Add options to the settings modal to enable these settings

- - -

## Original post

Would love it if the Mastodon frontend had the following options:

- `reduce_animation`: Removes all the CSS transitions, spinning effects, etc. on the frontend. Conserves resources and is less distracting.
- `no_transparency`: Eliminate all semi-opaque elements from the UI and make the media lightbox an opaque colour.
- `high_contrast`: Increases the contrast of UI elements.
- `light_mode`: Dark text on a light background instead of vice-versa.

All of this can be implemented through CSS but it will be a chore, and then there's the matter of activating/deactivating these options.
