### ISSUE TITLE
[FATAL tini (7)] exec node failed: No such file or directory

### ISSUE THREAD

**Issue by MFYDev** [glitch-soc/mastodon#2557]
### Steps to reproduce the problem

1. Install the latest nightly build
2. check the log of the streaming service
3. see this issue
...

### Expected behaviour

it should not displaying this error

### Actual behaviour

It is showing this error although seems like everything is still working fine

### Mastodon version

latest nightly build

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by ClearlyClaire** [comment]
Hi! As pointed out in https://github.com/glitch-soc/mastodon/issues/2525, the streaming server has been split out of the main docker image, there is now a `mastodon-streaming` docker image in addition to `mastodon`.

**Comment by MFYDev** [comment]
Thank you so much for the answer Claire, so is there anyway that we can fix this error or just let it be because it's working fine?

**Comment by ClearlyClaire** [comment]
I don't know how you are using the docker images, but you need to use the `mastodon-streaming` one to start the streaming service!

**Comment by MFYDev** [comment]
Hi Claire I am following and using the glitch mastodon docker-compose and that's all I am using. this log actually comes from the mastodon-streaming container. That's why I am confused. The container seems like is running well. Just noticed this log continuously so I reported here

**Comment by ClearlyClaire** [comment]
The `docker-compose` file points at upstream's latest release, so I assume you build the images yourself.

Try the following change?
```patch
diff --git a/docker-compose.yml b/docker-compose.yml
index 93451d9611..8c74914791 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -76,7 +76,7 @@ services:
       - ./public/system:/mastodon/public/system
 
   streaming:
-    build: .
+    build: ./streaming
     image: ghcr.io/mastodon/mastodon:v4.2.0
     restart: always
     env_file: .env.production

```

**Comment by MFYDev** [comment]
Hi Claire I am directly using the latest release actually without changing anything. I did not build anything.

To give you more info, this is the docker compose file I am using:

```yml
version: '3'
services:
  db:
    restart: always
    image: postgres:14-alpine
    container_name: mastodon-db
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: always
    image: redis:7-alpine
    container_name: mastodon-redis
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    # build: .
    image: ghcr.io/glitch-soc/mastodon:nightly
    restart: always
    container_name: mastodon-web
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '127.0.0.1:9875:3000'
    depends_on:
      - db
      - redis
      # - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    # build: .
    image: ghcr.io/glitch-soc/mastodon:nightly
    restart: always
    container_name: mastodon-streaming
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - db
      - redis

  sidekiq:
    # build: .
    image: ghcr.io/glitch-soc/mastodon:nightly
    restart: always
    container_name: mastodon-sidekiq
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network

networks:
  external_network:
  internal_network:
    internal: true#
```

**Comment by MFYDev** [comment]
And here below is the screenshot for the error:
<img width="656" alt="image" src="https://github.com/glitch-soc/mastodon/assets/53750381/08395259-cbc4-422d-a32b-341e3a298fea">

**Comment by jordemort** [comment]
@MFYDev Change this:

```yaml
  streaming:
    # build: .
    image: ghcr.io/glitch-soc/mastodon:nightly
```

...to this...

```yaml
  streaming:
    # build: .
    image: ghcr.io/glitch-soc/mastodon-streaming:nightly
```
