### ISSUE TITLE
The light/high contrast theme feels too busy

### ISSUE THREAD

**Issue by yipdw** [glitch-soc/mastodon#532]
@MightyPork pointed out that the addition of #471 makes the light theme feels too busy.  Here are two screenshots of the same status in the light theme:

![screenshot_20180604_102739](https://user-images.githubusercontent.com/3859/40926574-1d688b60-67e2-11e8-83e3-cb5685024749.png) 

And the default dark theme:
![screenshot_20180604_102755](https://user-images.githubusercontent.com/3859/40926579-1f92f11e-67e2-11e8-8f87-8d910e5e25e1.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by MightyPork** [comment]
here is my userstyle fix for this:

```css
.status__info__icons {
    color: #8f9dab;
}
.status__collapse-button {
    color: #727C85; // darker because it's too thin otherwise
}
```
